export const aisles = [
    { label: "2", value: 2 },
    { label: "3", value: 3 },
    { label: "4", value: 4 },
    { label: "5", value: 5 },
    { label: "6", value: 6 },
    { label: "7", value: 7 },
    { label: "8", value: 8 },
    { label: "9", value: 9 },
    { label: "10", value: 10 },
  ];

  export const bays = [
    { label: "A1", value: "A1" },
    { label: "A2", value: "A2" },
    { label: "A3", value: "A3" },
    { label: "A4", value: "A4" },
    { label: "A5", value: "A5" },
    { label: "A6", value: "A6" },
    { label: "A7", value: "A7" },
    { label: "A8", value: "A8" },
    { label: "A9", value: "A9" },
    { label: "A10", value: "A10" },
    { label: "A11", value: "A11" },
    { label: "A12", value: "A12" },
    { label: "A13", value: "A13" },
    { label: "A14", value: "A14" },
    { label: "A15", value: "A15" },
    { label: "A16", value: "A16" },
    { label: "A17", value: "A17" },
    { label: "A18", value: "A18" },
    { label: "A19", value: "A19" },
    { label: "A20", value: "A20" },
    { label: "B1", value: "B1" },
    { label: "B2", value: "B2" },
    { label: "B3", value: "B3" },
    { label: "B4", value: "B4" },
    { label: "B5", value: "B5" },
    { label: "B6", value: "B6" },
    { label: "B7", value: "B7" },
    { label: "B8", value: "B8" },
    { label: "B9", value: "B9" },
    { label: "B10", value: "B10" },
    { label: "B11", value: "B11" },
    { label: "B12", value: "B12" },
    { label: "B13", value: "B13" },
    { label: "B14", value: "B14" },
    { label: "B15", value: "B15" },
    { label: "B16", value: "B16" },
    { label: "B17", value: "B17" },
    { label: "B18", value: "B18" },
    { label: "B19", value: "B19" },
    { label: "B20", value: "B20" },
    { label: "C1", value: "C1" },
    { label: "C2", value: "C2" },
    { label: "C3", value: "C3" },
    { label: "C4", value: "C4" },
    { label: "C5", value: "C5" },
    { label: "C6", value: "C6" },
    { label: "C7", value: "C7" },
    { label: "C8", value: "C8" },
    { label: "C9", value: "C9" },
    { label: "C10", value: "C10" },
    { label: "C11", value: "C11" },
    { label: "C12", value: "C12" },
    { label: "C13", value: "C13" },
    { label: "C14", value: "C14" },
    { label: "C15", value: "C15" },
    { label: "C16", value: "C16" },
    { label: "C17", value: "C17" },
    { label: "C18", value: "C18" },
    { label: "C19", value: "C19" },
    { label: "C20", value: "C20" },
    { label: "D1", value: "D1" },
    { label: "D2", value: "D2" },
    { label: "D3", value: "D3" },
    { label: "D4", value: "D4" },
    { label: "D5", value: "D5" },
    { label: "D6", value: "D6" },
    { label: "D7", value: "D7" },
    { label: "D8", value: "D8" },
    { label: "D9", value: "D9" },
    { label: "Trailer", value: "Trailer" },
  ];

  export const sides = [
    { label: "Front", value: "Front" },
    { label: "Back", value: "Back" },
    { label: "Endcap", value: "Endcap" },
  ];

  export const sortData = [
    {
      label: "Aisle",
      value: "aisle",
    },
    {
      label: "Bay",
      value: "bay",
    },
  ];